# Generated by Django 3.0.7 on 2022-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='date_derniere_operation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
