# Generated by Django 3.0.7 on 2022-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0002_auto_20220420_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='derniere_operation',
            field=models.TextField(default='Aucune Operation'),
        ),
    ]
