# Generated by Django 3.0.7 on 2022-04-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0003_auto_20220420_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='derniere_operation',
            field=models.CharField(default='Aucune Operation', max_length=255),
        ),
    ]
