# Generated by Django 3.0.7 on 2022-04-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0004_auto_20220420_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='date_derniere_operation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
