# Generated by Django 3.0.7 on 2022-04-20 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0006_auto_20220420_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affectation',
            old_name='user_id',
            new_name='user',
        ),
    ]
