# Generated by Django 3.0.7 on 2022-04-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fonctions', '0001_initial'),
        ('affectations', '0001_initial'),
        ('directions', '0001_initial'),
        ('centres_cout', '0001_initial'),
        ('villes', '0001_initial'),
        ('contrats', '0001_initial'),
        ('entites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField()),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('cin', models.CharField(max_length=255)),
                ('date_entree', models.DateField()),
                ('situation_familiale', models.CharField(choices=[('Marié(e)', 'Marié(e)'), ('Célibataire', 'Célibataire')], max_length=11)),
                ('nombre_enfant', models.IntegerField()),
                ('charge_familiale', models.IntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('nationalite', models.TextField()),
                ('cnss', models.CharField(max_length=255)),
                ('salaire', models.FloatField()),
                ('numero_compte', models.IntegerField()),
                ('participation', models.CharField(max_length=255)),
                ('date_sortie', models.DateField()),
                ('derniere_operation', models.TextField()),
                ('date_derniere_operation', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affectations.Affectation')),
                ('centre_cout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centres_cout.CentreCout')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrats.Contrat')),
                ('delegue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.Employe')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directions.Direction')),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entites.Entite')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonctions.Fonction')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villes.Ville')),
            ],
            options={
                'db_table': 'employe',
                'managed': True,
                'unique_together': {('matricule', 'entite')},
            },
        ),
    ]
