# Generated by Django 3.0.7 on 2022-04-20 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonctions', '0002_auto_20220420_1030'),
        ('employes', '0003_auto_20220420_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='fonction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonctions.Fonction'),
        ),
    ]
