# Generated by Django 3.0.7 on 2022-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0004_auto_20220420_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='participation',
            field=models.IntegerField(),
        ),
    ]
