# Generated by Django 3.0.7 on 2022-04-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0005_auto_20220420_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
