# Generated by Django 3.0.7 on 2022-04-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0007_auto_20220420_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='user_id',
            new_name='user',
        ),
    ]
