# Generated by Django 3.0.7 on 2022-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('derniere_operation', models.TextField()),
                ('date_derniere_operation', models.DateField()),
            ],
            options={
                'db_table': 'entite',
                'managed': False,
            },
        ),
    ]
