# Generated by Django 3.0.7 on 2022-03-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('fonction_id', models.AutoField(primary_key=True, serialize=False)),
                ('fonction_designation', models.CharField(max_length=255)),
                ('fonction_description', models.CharField(blank=True, max_length=255, null=True)),
                ('derniere_operation', models.TextField()),
                ('date_derniere_operation', models.DateField()),
            ],
            options={
                'db_table': 'fonction',
                'managed': False,
            },
        ),
    ]
